# Generated by Django 4.1.3 on 2022-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="customer_name",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="login",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
