# Generated by Django 4.1.3 on 2022-12-15 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_customer_name_login_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="address",
        ),
    ]
