# Generated by Django 4.1.3 on 2022-12-16 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_login_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="password",
        ),
    ]
