# Generated by Django 4.1.3 on 2022-12-21 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0005_alter_changepassword_user_alter_event_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Size",
            new_name="SizesSelected",
        ),
    ]
