# Generated by Django 4.1.3 on 2022-12-22 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0006_rename_size_sizesselected"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sleevelength",
                    models.CharField(default=0, max_length=150, null=True),
                ),
                ("chestaround", models.CharField(default=0, max_length=150, null=True)),
                ("waistAround", models.CharField(default=0, max_length=150, null=True)),
                (
                    "LengthTrouser",
                    models.CharField(default=0, max_length=150, null=True),
                ),
                ("hip", models.CharField(default=0, max_length=150, null=True)),
                (
                    "WaistForTrouser",
                    models.CharField(default=0, max_length=150, null=True),
                ),
                ("thighs", models.CharField(default=0, max_length=150, null=True)),
                ("hem", models.CharField(default=0, max_length=150, null=True)),
                ("size", models.CharField(blank=True, max_length=3, null=True)),
                ("date", models.DateField()),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
