# Generated by Django 4.1.3 on 2022-12-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_orderdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
