# Generated by Django 4.1.3 on 2022-12-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_orderdetails_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.RemoveField(
            model_name="event",
            name="product",
        ),
        migrations.RemoveField(
            model_name="event",
            name="user",
        ),
        migrations.RemoveField(
            model_name="measurements",
            name="product",
        ),
        migrations.RemoveField(
            model_name="measurements",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sizesselected",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sizesselected",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="user",
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="size",
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name="AddToCart",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="Measurements",
        ),
        migrations.DeleteModel(
            name="SizesSelected",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
