# Generated by Django 4.1.3 on 2022-12-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_remove_cart_product_remove_cart_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AvailableSizes",
            new_name="AvailableSizesPant",
        ),
        migrations.RenameField(
            model_name="availablesizespant",
            old_name="size",
            new_name="size_pant",
        ),
        migrations.CreateModel(
            name="AvailableSizesShirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_shirt", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.product",
                    ),
                ),
            ],
        ),
    ]
