# Generated by Django 4.1.3 on 2022-12-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_rename_availablesizes_availablesizespant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changepassword",
            name="user",
        ),
        migrations.DeleteModel(
            name="Login",
        ),
        migrations.RemoveField(
            model_name="orderdetails",
            name="user",
        ),
        migrations.AddField(
            model_name="orderdetails",
            name="Cart_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="orderdetails",
            name="total",
            field=models.CharField(default=0, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name="ChangePassword",
        ),
    ]
