# Generated by Django 4.1.3 on 2022-12-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_rename_cart_id_orderdetails_cart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="total",
            field=models.FloatField(default=0, max_length=150, null=True),
        ),
    ]
