# Generated by Django 4.1.3 on 2022-12-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_alter_orderdetails_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="measurements_needed",
            field=models.BooleanField(default=False),
        ),
    ]
